PREPROCESSOR=sass
SCSS_FOLDER=scss
CSS_FOLDER=build
BLOG_FOLDER=blog
SCSS_FILES=$(SCSS_FOLDER)/master.scss $(BLOG_FOLDER)/$(SCSS_FOLDER)/master.scss


build : $(SCSS_FILES)
	$(PREPROCESSOR) $(SCSS_FOLDER)/master.scss $(CSS_FOLDER)/master.css	
	$(PREPROCESSOR) $(BLOG_FOLDER)/$(SCSS_FOLDER)/master.scss $(BLOG_FOLDER)/$(CSS_FOLDER)/master.css