* Why is VIM one of the best text editors
/2021-04-16 - Edited 2021-07-17/

/[[why_is_vim_one_of_the_best_text_editors.html][Raw article]]/

In this post, I will explain why VIM is one of the best text editors in my opinion.

+ VIM is ergonomic and powerful . I mean, /really/ ergonomic. You don't need to move your fingers everywhere on your keyboard to do a small thing, all the keybindings are grouped around the *home-row*, therefore you can leave your hands at the same place during your whole editing session. You don't need to type monstruous keybindings like ~Ctrl + Shift + =~. Moreover, the mode system allows you to do loads of things with a few keys. Its power also comes with macros and its scripting language.


+ VIM is *definitely NOT* difficult to use, but only if you know how to read, if you don't, I encourage you to [[https://www.learnreading.com/][learn]]. 

  Seriously, the meme « LMAO I'm trying to exit VIM since 4 years » is just stupid as the information is written on the start page (yes, try running the ~intro~ command or running VIM without any options, and you'll see). 

  When you install VIM, you also install the ~vimtutor~, which is a complete tutorial on how to use VIM, and it is translated in dozens of languages (~vimtutor <language_code>~). Then, if you find a new command and don't understand it, just run ~:help <command>~, and you'll get a detailed help. 
 
  If you want to learn « advanced » things such as VimL, to populate your ~.vimrc~ or to write plugins, you can use this [[https://learnvimscriptthehardway.stevelosh.com][great course by Steve Losh]]. 

  TL;DR: VIM is complex, but not uneasy.


+ VIM is really light. Both in features, disk space or memory usage. It does not use Electron or run Chromium instances and doesn't come out of the box with a web browser (I'm not aiming to anybody) nor a Git client. If you're missing a feature, it is almost surely covered by one of the thousands of plugins made by the VIM community.
